"""add support case response fields

Revision ID: ab5cdd984c28
Revises: 526cf63d194d
Create Date: 2026-09-28 12:49:53.469664

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab5cdd984c28'
down_revision: str | None = '526cf63d194d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_cases', sa.Column('response', sa.Text(), nullable=True))
    op.add_column('support_cases', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_cases', 'resolved_at')
    op.drop_column('support_cases', 'response')
    # ### end Alembic commands ###
